version: '3.9'
services:
  martial-art-manager-api:
    build:
      context: ./
      args:
        - DEBUGGER=True
    env_file :
      - .env
    ports:
      - 5000:5000
    container_name: api
    working_dir: "/src"
    volumes:
      - ./:/src
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.2.7-bionic
    hostname: mongo
    container_name: mongo
    ports:
      - 27017:27017
    command: mongod
    expose:
      - 27017

  redis:
    image: redis:6.0.6-alpine
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379